pyproject: add missing requests dependency
Without requests `fedora-repro-build` throws an exception:

Traceback (most recent call last):
  File "/usr/bin/fedora-repro-build", line 3, in <module>
    from fedora_repro.builder import main
  File "/usr/lib/python3.14/site-packages/fedora_repro/builder.py", line 24, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'